apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-secret-deployment
  labels:
    app: kube-secret
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-secret
  template:
    metadata:
      labels:
        app: kube-secret
    spec:
      containers:
      - name: kube-secret
        image: lionpooh/kube-secret:0.0.2
        imagePullPolicy: Never
        volumeMounts:
          - name: kube-secret-volume
            mountPath: /config/
        env:
          - name: KUBE_NAME
            valueFrom:
              secretKeyRef:
                name: custom-secret-custom.custom
                key: kubename
      volumes:
        - name: kube-secret-volume
          configMap:
            name: kube-secret-configmap
