apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-secret-deployment
  labels:
    app: kube-secret
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-secret
  template:
    metadata:
      labels:
        app: kube-secret
    spec:
      containers:
      - name: kube-secret
        image: lionpooh/kube-secret:0.0.2
        imagePullPolicy: Never
        env:
          - name: KUBE_NAME
            valueFrom:
              secretKeyRef:
                name: custom-secret-5m9766khm5
                key: kubename
          - name: KUBE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: custom-secret-5m9766khm5
                key: kubepassword
